# Generated by Django 2.2.5 on 2019-09-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='image')),
                ('price', models.FloatField(default=0, verbose_name='price')),
            ],
        ),
    ]
