# Generated by Django 2.2.4 on 2019-10-17 14:57

import MyMenu.apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190928_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_day_dish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=MyMenu.apps.menu.models.OverwriteStorage(), upload_to='dishes/', verbose_name='image'),
        ),
    ]
