# Generated by Django 2.2.4 on 2019-10-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'suggestion', 'verbose_name_plural': 'suggestions'},
        ),
    ]
