# Generated by Django 2.2.4 on 2019-10-19 06:37

import MyMenu.apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20191017_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, storage=MyMenu.apps.menu.models.OverwriteStorage(), upload_to='drinks/', verbose_name='image')),
                ('price', models.FloatField(default=0, verbose_name='price')),
            ],
            options={
                'verbose_name': 'drink',
                'verbose_name_plural': 'drinks',
            },
        ),
    ]
