# Generated by Django 2.2.4 on 2019-10-17 15:43

import MyMenu.apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20191017_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, storage=MyMenu.apps.menu.models.OverwriteStorage(), upload_to='dishes/categories', verbose_name='image')),
            ],
            options={
                'verbose_name': 'dish category',
                'verbose_name_plural': 'dish categories',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete='dish category', related_name='dishes', to='menu.DishCategory'),
            preserve_default=False,
        ),
    ]
