# Generated by Django 2.2.4 on 2019-10-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='is_day_dish',
        ),
        migrations.CreateModel(
            name='DayDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_dishes', to='menu.Drink', verbose_name='drink')),
                ('garnish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Dish', verbose_name='garnish')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_dishes', to='menu.Dish', verbose_name='main dish')),
            ],
            options={
                'verbose_name': 'day dish',
                'verbose_name_plural': 'day dishes',
            },
        ),
    ]
