# Generated by Django 2.2.4 on 2019-10-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydish',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
