# Generated by Django 2.2.4 on 2019-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20191026_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydish',
            name='is_day_dish',
            field=models.BooleanField(default=False),
        ),
    ]
