# Generated by Django 2.2.4 on 2019-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20191026_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydish',
            name='is_day_dish',
            field=models.BooleanField(default=False, verbose_name='is day dish'),
        ),
    ]
