# Generated by Django 2.2.4 on 2019-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_paymentmethod_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='promotion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='promotion'),
        ),
    ]
